[package]
name = "lazyman_trading"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = [
    "rustls-tls",
], default-features = false }
rust_decimal = "1.37.2"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.142"
tokio = "1.47.1"
